// All player-visible strings live here. Switching language is a data change,
// never a code change (game-design-system §10.3).
export const STR = {
  title: "PUTT OR DIE",
  tagline: "A mini-golf roulette in the Dealer's basement.",
  start: "RACK 'EM UP",
  howTitle: "HOW TO SURVIVE",
  how: [
    "Aim with A / D or ← →  (drag on touch). The camera swings behind your ball.",
    "Tap SPACE / PUTT to start the power meter, tap again to fire.",
    "Sink the ball fast. Every stroke OVER PAR draws a shell from the Dealer's gun.",
    "LIVE shell = you eat lead (−1 ❤). BLANK = a lucky click.",
    "Sink it and you turn the gun on the Dealer — survive and bank the shells you dodged.",
    "Mind the spike-mines, water and spinning bars. Grab pickups. Don't run dry.",
  ],
  items: {
    beer:    { name: "Beer",      glyph: "🍺", blurb: "Rack the gun: eject the next shell unfired." },
    pills:   { name: "Pills",     glyph: "💊", blurb: "Expired meds: heal big, or it backfires." },
    smoke:   { name: "Cigarette", glyph: "🚬", blurb: "Steady the nerves: +1 ❤." },
    glass:   { name: "Magnifier", glyph: "🔍", blurb: "Inspect the next shell in the chamber." },
    saw:     { name: "Hand-Saw",  glyph: "🪚", blurb: "Saw the barrel: next putt is a power shot." },
    cuffs:   { name: "Handcuffs", glyph: "⛓️", blurb: "Cuff the machinery: freeze movers this hole." },
  },
  hud: { floor: "FLOOR", hole: "HOLE", par: "PAR", stroke: "STROKE", bag: "BAG", live: "LIVE", blank: "BLANK", chamber: "CHAMBER" },
  putt: "PUTT",
  rewardTitle: "THE DEALER DEALS",
  rewardSub: "Pick your poison.",
  reward: { heal: "Patch Up", healSub: "+2 ❤", tokens: "Chips", tokensSub: "+%n in the pot" },
  over: "YOU DIED",
  overSub: "The basement keeps you.",
  again: "BACK TO THE TABLE",
  depth: "DEPTH",
  chips: "CHIPS",
  best: "BEST",
  // Toasts
  bang: "BANG!  −1 ❤",
  click: "*click*  blank.",
  sunk: "SUNK IT!",
  birdie: "BIRDIE!  Under par.",
  splash: "SPLASH — water. +1 stroke.",
  spike: "SPIKE MINE!  −1 ❤",
  dry: "OUT OF SHELLS — conceded. −2 ❤",
  saw: "Barrel sawed — POWER PUTT loaded.",
  cuffed: "Machinery cuffed.",
  ejected: "Shell ejected.",
  healed: "Nerves steadied.",
  pillsGood: "The meds hit right. +2 ❤",
  pillsBad: "Bad batch... −1 ❤, hands shaking.",
  glass: "Next shell: %s",
  gotItem: "Picked up: %s",
  bagFull: "Bag full — pickup skipped.",
  shellLive: "LIVE",
  shellBlank: "BLANK",
  // Dealer barks, picked by RNG
  dealer: [
    "\"Tee off, meat.\"",
    "\"Two in the chamber. Maybe.\"",
    "\"You feel lucky? Putt.\"",
    "\"The house always sinks.\"",
    "\"Sloppy. The gun gets hungry.\"",
    "\"Beautiful. Do it again.\"",
    "\"Par is mercy. I'm not.\"",
    "\"Tick. Tick. Swing.\"",
    "\"One stroke too many and we talk.\"",
    "\"Down we go.\"",
  ],
};
