import { chromium } from "playwright-core";
const EXE="/opt/pw-browsers/chromium-1194/chrome-linux/chrome";
const OUT="/tmp/claude-0/-home-user-Putt/1bc6d0db-2c06-5ff4-8f66-be6cf2cc218f/scratchpad";
const b=await chromium.launch({executablePath:EXE,headless:true,args:["--no-sandbox","--use-gl=angle","--use-angle=swiftshader","--ignore-gpu-blocklist","--enable-unsafe-swiftshader","--disable-dev-shm-usage"]});
const p=await b.newPage({viewport:{width:1280,height:720}});
await p.goto("http://localhost:8000/index.html",{waitUntil:"networkidle"});
await p.waitForTimeout(400);
const info=await p.evaluate(()=>{const g=window.__game; g.start(); g.money=64; g.depth=2; g.openShop(); return {state:g.state, stock:g._stock, money:g.money};});
console.log("SHOP:",JSON.stringify(info));
await p.waitForTimeout(200);
await p.screenshot({path:OUT+"/shot-shop.png"});
await b.close();
